"""empty message

Revision ID: 0cfbad09764a
Revises: baa5a0d2363d
Create Date: 2018-12-10 18:17:15.513035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfbad09764a'
down_revision = 'baa5a0d2363d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'role', sa.Column('created_user_id', sa.Integer(), nullable=True))
    op.add_column(u'role', sa.Column('modified_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'user', ['modified_user_id'], ['id'])
    op.create_foreign_key(None, 'role', 'user', ['created_user_id'], ['id'])
    op.add_column(u'user', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'review_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'type_id')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column(u'role', 'modified_user_id')
    op.drop_column(u'role', 'created_user_id')
    op.drop_table('review_type')
    # ### end Alembic commands ###
