"""empty message

Revision ID: 14ce0204292b
Revises: d15588b4a99d
Create Date: 2018-12-11 14:53:21.372182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ce0204292b'
down_revision = 'd15588b4a99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('team', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'desc')
    op.drop_column('project', 'desc')
    op.drop_column('company', 'desc')
    # ### end Alembic commands ###
