"""empty message

Revision ID: 3c3f2fe36a21
Revises: 99100c610a3e
Create Date: 2018-12-15 15:45:36.974126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c3f2fe36a21'
down_revision = '99100c610a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'comment_ibfk_4', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'question', ['question_id'], ['id'])
    op.drop_column('comment', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(u'comment_ibfk_4', 'comment', 'review_type', ['type_id'], ['id'])
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###
