"""empty message

Revision ID: 5bc940e34096
Revises: 655b6f5c51c3
Create Date: 2019-01-01 09:20:16.563909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc940e34096'
down_revision = '655b6f5c51c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('company', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('team', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('team', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'rating_count')
    op.drop_column('team', 'comment_count')
    op.drop_column('company', 'rating_count')
    op.drop_column('company', 'comment_count')
    # ### end Alembic commands ###
