"""empty message

Revision ID: 99100c610a3e
Revises: d36e6e98140c
Create Date: 2018-12-13 15:50:36.975372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99100c610a3e'
down_revision = 'd36e6e98140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
