"""empty message

Revision ID: d0600adf7057
Revises: 0cfbad09764a
Create Date: 2018-12-10 18:28:03.052988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0600adf7057'
down_revision = '0cfbad09764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    # ### end Alembic commands ###
