"""empty message

Revision ID: d36e6e98140c
Revises: 6d2808fe49c8
Create Date: 2018-12-13 11:28:25.822097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd36e6e98140c'
down_revision = '6d2808fe49c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8mb4_bin', length=255), nullable=True),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('desc', mysql.TEXT(collation=u'utf8mb4_bin'), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'project_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'project_ibfk_2'),
    sa.ForeignKeyConstraint(['type_id'], [u'review_type.id'], name=u'project_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_bin',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
