"""empty message

Revision ID: ec6944f4baa4
Revises: e091ef914393
Create Date: 2018-12-21 10:21:23.775245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6944f4baa4'
down_revision = 'e091ef914393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('keywords', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'keywords')
    # ### end Alembic commands ###
